# Generated by Django 5.1.7 on 2025-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prdct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, unique=True, verbose_name="Назва користувача")),
                ('price', models.CharField(max_length=100, verbose_name='Ціна товару')),
                ('type', models.EmailField(max_length=254, verbose_name='Категорія товару')),
            ],
        ),
    ]
