# Generated by Django 5.1.7 on 2025-04-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prdct',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterField(
            model_name='prdct',
            name='product',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='prdct',
            name='type',
            field=models.EmailField(max_length=100, verbose_name='Категорія товару'),
        ),
    ]
