# Generated by Django 5.2 on 2025-05-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
